import {
  Dashboard,
  Folder,
  PathLabs,
  ReportBills,
  Person,
  Tests,
  Hospital,
  AddPathLab,
  AddFolder,
  Alarm,
  AddPerson,
  ContactLeads,
} from '../assets/icons';

const adminActions = [
  {
    label: 'Add a Package',
    icon: AddFolder,
    outlined: true,
    path: '/super-admin/packages/add',
  },
  {
    label: 'Add a Path Lab',
    icon: AddPathLab,
    containedButton: true,
    path: '/super-admin/path-labs/add',
  },
];

const assistantAdminActions = [
  {
    label: 'Add a Package',
    icon: AddFolder,
    outlined: true,
    path: '/assistant-admin/packages/add',
  },
  {
    label: 'Add a Path Lab',
    icon: AddPathLab,
    containedButton: true,
    path: '/assistant-admin/path-labs/add',
  },
];

const labOwnerActions = [
  {
    label: 'Add New Appointment',
    icon: Alarm,
    outlined: true,
    path: '/lab-admin/add-appointment',
  },
  {
    label: 'Add New Patient',
    icon: AddPerson,
    containedButton: true,
    path: '/lab-admin/patients/add',
  },
];

const labUserActions = [
  {
    label: 'Add New Appointment',
    icon: Alarm,
    outlined: true,
    path: '/lab/add-appointment',
  },
  {
    label: 'Add New Patient',
    icon: AddPerson,
    containedButton: true,
    path: '/lab/patients/add',
  },
];

const adminLinks = [
  {
    label: 'Dashboard',
    path: `/super-admin/dashboard`,
    icon: Dashboard,
    key: 'dashboard',
    role: ['super-admin'],
    actions: adminActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'Overview',
        path: `/super-admin/dashboard/overview`,
        key: 'dashboard',
      },
      {
        label: 'Statistics',
        path: `/super-admin/dashboard/statistics`,
        key: 'dashboard',
      },
      {
        label: 'Demo Requests',
        path: `/super-admin/dashboard/demo-request`,
        key: 'dashboard',
      },
    ],
  },
  {
    label: 'Path Labs',
    path: `/super-admin/path-labs`,
    icon: PathLabs,
    key: 'path-labs',
    role: ['super-admin'],
    actions: adminActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'List of Path Labs',
        path: `/super-admin/path-labs/list`,
        key: 'path-labs',
      },
      {
        label: 'Add a Path Lab',
        path: `/super-admin/path-labs/add`,
        key: 'path-labs',
      },
    ],
  },
  {
    label: 'Lab Details',
    path: `/super-admin/lab-details`,
    key: 'lab-details',
    role: ['super-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [
      {
        label: 'Main office details',
        path: `/super-admin/lab-details/main-office-details`,
        key: 'lab-details',
      },
      {
        label: 'Branch Details',
        path: `/super-admin/lab-details/branch-details`,
        key: 'lab-details',
      },
      {
        label: 'Package Details',
        path: `/super-admin/lab-details/package-details`,
        key: 'lab-details',
      },
    ],
  },
  {
    label: 'Tests',
    path: `/super-admin/tests`,
    icon: Tests,
    key: 'tests',
    role: ['super-admin'],
    isSidebarMenu: true,
    tabData: [
      {
        label: 'Master List',
        path: `/super-admin/tests/list`,
        key: 'tests',
      },
      {
        label: 'Categories',
        path: `/super-admin/tests/categories`,
        key: 'tests',
      },
      {
        label: 'Units',
        path: `/super-admin/tests/units`,
        key: 'tests',
      },
      {
        label: 'Sample Type',
        path: `/super-admin/tests/sample-type`,
        key: 'tests',
      },
    ],
  },
  {
    label: 'Packages',
    path: `/super-admin/packages`,
    icon: Folder,
    key: 'packages',
    role: ['super-admin'],
    actions: adminActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'List of Packages',
        path: `/super-admin/packages/list`,
        key: 'packages',
      },
      {
        label: 'Add a Package',
        path: `/super-admin/packages/add`,
        key: 'packages',
      },
    ],
  },
  {
    label: 'Patients (Users)',
    path: `/super-admin/patient`,
    icon: Person,
    key: 'patient',
    role: ['super-admin'],
    actions: adminActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'List of Patients',
        path: `/super-admin/patient/list`,
        key: 'patient',
      },
    ],
  },
  {
    label: 'Upgrade Package',
    noSidebarLabel: true,
    path: `/super-admin/upgrade-package`,
    key: 'upgrade-package',
    role: ['super-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  {
    label: 'Add Test',
    noSidebarLabel: true,
    path: `/super-admin/add-test`,
    key: 'add-test',
    role: ['super-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/super-admin/tests/list',
      label: 'Back To Master List',
    },
  },
  {
    label: 'View Test',
    noSidebarLabel: true,
    path: `/super-admin/view-test/:testId`,
    key: 'view-test',
    role: ['super-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/super-admin/tests/list',
      label: 'Back To Master List',
    },
  },
  {
    label: 'Edit Test',
    noSidebarLabel: true,
    path: `/super-admin/edit-test/:testId`,
    key: 'edit-test',
    role: ['super-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/super-admin/tests/list',
      label: 'Back To Master List',
    },
  },
  {
    label: 'Contact Leads',
    path: `/super-admin/contact-leads`,
    icon: ContactLeads,
    key: 'contact-leads',
    role: ['super-admin'],
    actions: adminActions,
    isSidebarMenu: true,
    tabData: [],
  },
  {
    label: 'User Management',
    path: `/super-admin/setting/user-management`,
    isSetting: true,
    key: 'user-management',
    role: ['super-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  {
    label: 'My Profile',
    path: `/super-admin/setting/my-profile`,
    isSetting: true,
    key: 'my-profile',
    role: ['super-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  // {
  //   label: 'App Settings',
  //   path: `/super-admin/setting/app-settings`,
  //   isSetting: true,
  //   key: 'app-settings',
  //   role: ['super-admin'],
  //   actions: [],
  //   isSidebarMenu: false,
  //   tabData: [],
  // },
];

const assistantAdminLinks = [
  {
    label: 'Dashboard',
    path: `/assistant-admin/dashboard`,
    icon: Dashboard,
    key: 'dashboard',
    role: ['assistant-admin'],
    actions: assistantAdminActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'Overview',
        path: `/assistant-admin/dashboard/overview`,
        key: 'dashboard',
      },
      {
        label: 'Statistics',
        path: `/assistant-admin/dashboard/statistics`,
        key: 'dashboard',
      },
      {
        label: 'Demo Requests',
        path: `/assistant-admin/dashboard/demo-request`,
        key: 'dashboard',
      },
    ],
  },
  {
    label: 'Path Labs',
    path: `/assistant-admin/path-labs`,
    icon: PathLabs,
    key: 'path-labs',
    role: ['assistant-admin'],
    actions: assistantAdminActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'List of Path Labs',
        path: `/assistant-admin/path-labs/list`,
        key: 'path-labs',
      },
      {
        label: 'Add a Path Lab',
        path: `/assistant-admin/path-labs/add`,
        key: 'path-labs',
      },
    ],
  },
  {
    label: 'Lab Details',
    path: `/assistant-admin/lab-details`,
    key: 'lab-details',
    role: ['assistant-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [
      {
        label: 'Main office details',
        path: `/assistant-admin/lab-details/main-office-details`,
        key: 'lab-details',
      },
      {
        label: 'Branch Details',
        path: `/assistant-admin/lab-details/branch-details`,
        key: 'lab-details',
      },
      {
        label: 'Package Details',
        path: `/assistant-admin/lab-details/package-details`,
        key: 'lab-details',
      },
    ],
  },
  {
    label: 'Tests',
    path: `/assistant-admin/tests`,
    icon: Tests,
    key: 'tests',
    role: ['assistant-admin'],
    isSidebarMenu: true,
    tabData: [
      {
        label: 'Master List',
        path: `/assistant-admin/tests/list`,
        key: 'tests',
      },
      {
        label: 'Categories',
        path: `/assistant-admin/tests/categories`,
        key: 'tests',
      },
      {
        label: 'Units',
        path: `/assistant-admin/tests/units`,
        key: 'tests',
      },
      {
        label: 'Sample Type',
        path: `/assistant-admin/tests/sample-type`,
        key: 'tests',
      },
    ],
  },
  {
    label: 'Packages',
    path: `/assistant-admin/packages`,
    icon: Folder,
    key: 'packages',
    role: ['assistant-admin'],
    actions: assistantAdminActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'List of Packages',
        path: `/assistant-admin/packages/list`,
        key: 'packages',
      },
      {
        label: 'Add a Package',
        path: `/assistant-admin/packages/add`,
        key: 'packages',
      },
    ],
  },
  {
    label: 'Patients (Users)',
    path: `/assistant-admin/patient`,
    icon: Person,
    key: 'patient',
    role: ['assistant-admin'],
    actions: assistantAdminActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'List of Patients',
        path: `/assistant-admin/patient/list`,
        key: 'patient',
      },
    ],
  },
  {
    label: 'Upgrade Package',
    noSidebarLabel: true,
    path: `/assistant-admin/upgrade-package`,
    key: 'upgrade-package',
    role: ['assistant-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  {
    label: 'Add Test',
    noSidebarLabel: true,
    path: `/assistant-admin/add-test`,
    key: 'add-test',
    role: ['assistant-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/assistant-admin/tests/list',
      label: 'Back To Master List',
    },
  },
  {
    label: 'View Test',
    noSidebarLabel: true,
    path: `/assistant-admin/view-test/:testId`,
    key: 'view-test',
    role: ['assistant-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/assistant-admin/tests/list',
      label: 'Back To Master List',
    },
  },
  {
    label: 'Edit Test',
    noSidebarLabel: true,
    path: `/assistant-admin/edit-test/:testId`,
    key: 'edit-test',
    role: ['assistant-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/assistant-admin/tests/list',
      label: 'Back To Master List',
    },
  },
  {
    label: 'Contact Leads',
    path: `/assistant-admin/contact-leads`,
    icon: ContactLeads,
    key: 'contact-leads',
    role: ['assistant-admin'],
    actions: assistantAdminActions,
    isSidebarMenu: true,
    tabData: [],
  },
  {
    label: 'My Profile',
    path: `/assistant-admin/setting/my-profile`,
    isSetting: true,
    key: 'my-profile',
    role: ['assistant-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  // {
  //   label: 'App Settings',
  //   path: `/super-admin/setting/app-settings`,
  //   isSetting: true,
  //   key: 'app-settings',
  //   role: ['super-admin'],
  //   actions: [],
  //   isSidebarMenu: false,
  //   tabData: [],
  // },
];

const labOwnerLinks = [
  {
    label: 'Lab Details',
    path: `/lab-admin/setting/lab-details`,
    isSetting: true,
    key: 'lab-details',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [
      {
        label: 'Main office details',
        path: `/lab-admin/setting/lab-details/main-office-details`,
        key: 'lab-details',
      },
      {
        label: 'Branch Details',
        path: `/lab-admin/setting/lab-details/branch-details`,
        key: 'lab-details',
      },
      {
        label: 'Package Details',
        path: `/lab-admin/setting/lab-details/package-details`,
        key: 'lab-details',
      },
    ],
  },
  {
    label: 'Test Master',
    path: '/lab-admin/setting/tests',
    isSetting: true,
    key: 'tests',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [
      {
        label: 'Master List',
        path: `/lab-admin/setting/tests/list`,
        key: 'tests',
      },
      {
        label: 'Categories',
        path: `/lab-admin/setting/tests/categories`,
        key: 'tests',
      },
      {
        label: 'Units',
        path: `/lab-admin/setting/tests/units`,
        key: 'tests',
      },
      {
        label: 'Sample Type',
        path: `/lab-admin/setting/tests/sample-type`,
        key: 'tests',
      },
    ],
  },
  {
    label: 'Add Test',
    noSidebarLabel: true,
    path: `/lab-admin/setting/add-test`,
    key: 'add-test',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/lab-admin/setting/tests/list',
      label: 'Back To Master List',
    },
  },
  {
    label: 'View Test',
    noSidebarLabel: true,
    path: `/lab-admin/setting/view-test/:testId`,
    key: 'view-test',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/lab-admin/setting/tests/list',
      label: 'Back To Master List',
    },
  },
  {
    label: 'Edit Test',
    noSidebarLabel: true,
    path: `/lab-admin/setting/edit-test/:testId`,
    key: 'edit-test',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/lab-admin/setting/tests/list',
      label: 'Back To Master List',
    },
  },
  {
    label: 'Test Sets',
    path: '/lab-admin/setting/test-sets',
    isSetting: true,
    key: 'test-sets',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  {
    label: 'Edit main office details',
    noSidebarLabel: true,
    path: `/lab-admin/setting/edit-main-office-details`,
    isSetting: true,
    key: 'edit-main-office-details',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  {
    label: 'Add New Package',
    noSidebarLabel: true,
    path: `/lab-admin/setting/test-packages-add`,
    isSetting: true,
    key: 'test-packages-add',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: null,
      label: 'BACK TO PACKAGE LIST',
    },
  },
  {
    label: 'Edit Package Details',
    noSidebarLabel: true,
    path: `/lab-admin/setting/test-package-edit`,
    isSetting: true,
    key: 'test-package-edit',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: null,
      label: 'BACK TO PACKAGE LIST',
    },
  },
  {
    label: 'Add a Branch',
    noSidebarLabel: true,
    path: `/lab-admin/setting/add-branch-details`,
    isSetting: true,
    key: 'add-branch-details',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  {
    label: 'My Profile',
    path: `/lab-admin/setting/my-profile`,
    isSetting: true,
    key: 'my-profile',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  {
    label: 'Dashboard',
    path: `/lab-admin/dashboard`,
    icon: Dashboard,
    key: 'dashboard',
    role: ['lab-admin'],
    actions: labOwnerActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'Patients Overview',
        path: `/lab-admin/dashboard/overview`,
        key: 'dashboard',
      },
      {
        label: 'Lab Statistics',
        path: `/lab-admin/dashboard/lab-statistics`,
        key: 'dashboard',
      },
      {
        label: 'Appointments',
        path: `/lab-admin/dashboard/appointments`,
        key: 'dashboard',
      },
    ],
  },
  {
    label: 'Report Preview',
    noSidebarLabel: true,
    path: `/lab-admin/report-preview`,
    isSetting: true,
    key: 'report-preview',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/lab-admin/patients/list',
      label: 'BACK TO UPDATE REPORT',
    },
  },
  {
    label: 'Edit Patients',
    path: `/lab-admin/edit-patient/:patientId`,
    icon: Person,
    key: 'edit-patient',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  {
    label: 'Patients',
    path: `/lab-admin/patients`,
    icon: Person,
    key: 'patients',
    role: ['lab-admin'],
    actions: labOwnerActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'List of Patients',
        path: `/lab-admin/patients/list`,
        key: 'patients',
      },
      {
        label: 'Add New Patient',
        path: `/lab-admin/patients/add`,
        key: 'patients',
      },
    ],
  },
  {
    label: 'Referred Doctor',
    path: `/lab-admin/referred-doctor`,
    icon: Hospital,
    key: 'referred-doctor',
    role: ['lab-admin'],
    actions: labOwnerActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'List of Doctors',
        path: `/lab-admin/referred-doctor/list`,
        key: 'referred-doctor',
      },
      {
        label: 'Add a Doctor',
        path: `/lab-admin/referred-doctor/add`,
        key: 'referred-doctor',
      },
    ],
  },
  {
    label: 'Add an appointment',
    path: `/lab-admin/add-appointment`,
    key: 'add-appointment',
    role: ['lab-admin'],
    actions: labOwnerActions,
    isSidebarMenu: false,
  },
];

const labUserLinks = [
  {
    label: 'Branch Details',
    path: `/lab/setting/branch-details`,
    isSetting: true,
    key: 'branch-details',
    role: ['lab'],
    actions: [],
    tabData: [
      {
        label: 'Name & Address',
        path: `/lab/setting/branch-details/name-and-address`,
        key: 'branch-details',
      },
      {
        label: 'Branch Users',
        path: `/lab/setting/branch-details/branch-users`,
        key: 'branch-details',
      },
      {
        label: 'Report Letterhead & Sign',
        path: `/lab/setting/branch-details/report`,
        key: 'branch-details',
      },
    ],
  },
  {
    label: 'Test Master',
    path: '/lab/setting/tests',
    isSetting: true,
    key: 'tests',
    role: ['lab'],
    excludeRole : ['lab_technician'], // not to show for lab_technician 
    actions: [],
    isSidebarMenu: false,
    tabData: [
      {
        label: 'Master List',
        path: `/lab/setting/tests/list`,
        key: 'tests',
      },
      {
        label: 'Categories',
        path: `/lab/setting/tests/categories`,
        key: 'tests',
      },
      {
        label: 'Units',
        path: `/lab/setting/tests/units`,
        key: 'tests',
      },
      {
        label: 'Sample Type',
        path: `/lab/setting/tests/sample-type`,
        key: 'tests',
      },
    ],
  },
  {
    label: 'Add Test',
    noSidebarLabel: true,
    path: `/lab/setting/add-test`,
    key: 'add-test',
    role: ['lab'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/lab/setting/tests/list',
      label: 'Back To Master List',
    },
  },
  {
    label: 'View Test',
    noSidebarLabel: true,
    path: `/lab/setting/view-test/:testId`,
    key: 'view-test',
    role: ['lab'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/lab/setting/tests/list',
      label: 'Back To Master List',
    },
  },
  {
    label: 'Edit Test',
    noSidebarLabel: true,
    path: `/lab/setting/edit-test/:testId`,
    key: 'edit-test',
    role: ['lab'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/lab/setting/tests/list',
      label: 'Back To Master List',
    },
  },
  {
    label: 'Test Sets',
    path: '/lab/setting/test-sets',
    isSetting: true,
    key: 'test-sets',
    role: ['lab'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  {
    label: 'My Profile',
    path: `/lab/setting/my-profile`,
    isSetting: true,
    key: 'my-profile',
    role: ['lab'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  {
    label: 'Dashboard',
    path: `/lab/dashboard`,
    icon: Dashboard,
    key: 'dashboard',
    role: ['lab'],
    actions: labUserActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'Patients Overview',
        path: `/lab/dashboard/overview`,
        key: 'dashboard',
      },
      {
        label: 'Lab Statistics',
        path: `/lab/dashboard/lab-statistics`,
        key: 'dashboard',
      },
      {
        label: 'Appointments',
        path: `/lab/dashboard/appointments`,
        key: 'dashboard',
      },
    ],
  },
  {
    label: 'Report Preview',
    noSidebarLabel: true,
    path: `/lab/report-preview`,
    isSetting: true,
    key: 'report-preview',
    role: ['lab'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/lab/patients/list',
      label: 'BACK TO UPDATE REPORT',
    },
  },
  {
    label: 'Edit Patients',
    path: `/lab/edit-patient`,
    icon: Person,
    key: 'edit-patient',
    role: ['lab'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  {
    label: 'Patients',
    path: `/lab/patients`,
    icon: Person,
    key: 'patients',
    role: ['lab'],
    actions: labUserActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'List of Patients',
        path: `/lab/patients/list`,
        key: 'patients',
      },
      {
        label: 'Add New Patient',
        path: `/lab/patients/add`,
        key: 'patients',
      },
    ],
  },
  {
    label: 'Edit Doctor details',
    noSidebarLabel: true,
    path: `/lab-admin/referred-doctor-update`,
    key: 'referred-doctor-update',
    role: ['lab-admin'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  {
    label: 'Referred Doctor',
    path: `/lab/referred-doctor`,
    icon: Hospital,
    key: 'referred-doctor',
    role: ['lab'],
    actions: labUserActions,
    isSidebarMenu: true,
    tabData: [
      {
        label: 'List of Doctors',
        path: `/lab/referred-doctor/list`,
        key: 'referred-doctor',
      },
      {
        label: 'Add a Doctor',
        path: `/lab/referred-doctor/add`,
        key: 'referred-doctor',
      },
    ],
  },
  {
    label: 'Add New Package',
    noSidebarLabel: true,
    path: `/lab/setting/test-packages-add`,
    isSetting: true,
    key: 'test-packages-add',
    role: ['lab'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: null,
      label: 'BACK TO PACKAGE LIST',
    },
  },
  {
    label: 'Edit Package Details',
    noSidebarLabel: true,
    path: `/lab/setting/test-package-edit`,
    isSetting: true,
    key: 'test-package-edit',
    role: ['lab'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: null,
      label: 'BACK TO PACKAGE LIST',
    },
  },
  {
    label: 'Add an appointment',
    path: `/lab/add-appointment`,
    key: 'add-appointment',
    role: ['lab'],
    actions: labUserActions,
    isSidebarMenu: false,
  },
];

const patientLinks = [
  {
    label: 'Dashboard',
    path: `/patient/dashboard`,
    icon: Dashboard,
    key: 'dashboard',
    role: ['patient'],
    actions: [],
    isSidebarMenu: true,
    tabData: [],
  },
  {
    label: 'View Report',
    noSidebarLabel: true,
    path: `/patient/view-report`,
    isSetting: true,
    key: 'view-report',
    role: ['patient'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
    goBack: {
      url: '/patient/reports-and-bills',
      label: 'BACK TO LIST OF REPORTS & BILLS',
    },
  },
  {
    label: 'Reports & Bills',
    path: `/patient/reports-and-bills`,
    icon: ReportBills,
    key: 'reports-and-bills',
    role: ['patient'],
    actions: [],
    isSidebarMenu: true,
    tabData: [],
  },
  {
    label: 'Tracking Chart',
    path: `/patient/tracking-chart`,
    key: 'tracking-chart',
    role: ['patient'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
  {
    label: 'My Profile',
    path: `/patient/setting/my-profile`,
    isSetting: true,
    key: 'my-profile',
    role: ['patient'],
    actions: [],
    isSidebarMenu: false,
    tabData: [],
  },
];

const sideBarRoutes = [...adminLinks, ...assistantAdminLinks, ...labOwnerLinks, ...labUserLinks, ...patientLinks];

export default sideBarRoutes;
